### ISSUE TITLE
ensure that setup is idempotent; use case: openshift-sdn in a container

### ISSUE THREAD

**Issue by rajatchopra** [openshift/openshift-sdn#111]
There is logic today that if the docker linux bridge is already configured correctly, then the setup phase on the node is skipped. Ensure that this 'skip' still completes the steps that could be left behind by a possible earlier setup exit because docker daemon was restarted.

The scenario exists in the case where openshift-sdn-node is run as a docker container (privileged, of course). As soon as the 'setup sdn' restarts docker, the sdn process will end up killing itself leaving possibly unfinished tasks of the setup.

**Comment by marun** [comment]
Might a better title for this issue be 'ensure that setup is idempotent'?  i.e. It should be possible to run network setup multiple times and be assured of the correct outcome if it completes without error.
