### ISSUE TITLE
Forego use of docker bridge for IPAM: take advantage of kube status hook

### ISSUE THREAD

**Issue by rajatchopra** [openshift/openshift-sdn#112]
With kube status hooks in place, we can use a generic IPAM and forego the use of Docker Linux bridge entirely (for IPV4 at least).
The kube hook PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/9646
This will require that an IPAM server be configured and run in parallel to the SDN's main tracking process on the node.

**Comment by pravisankar** [comment]
Closing this issue in favor of trello card: https://trello.com/c/Df3tx5AW/112-move-ip-address-management-from-docker-to-openshift-sdn-support-ability-functionality
