### ISSUE TITLE
Find out NetworkManger implications on openshift SDN

### ISSUE THREAD

**Issue by pravisankar** [openshift/openshift-sdn#113]
Currently, we recommend NetworkManager to be turned off on every host (master/node): Host Preparation section in https://docs.openshift.org/latest/admin_guide/install/prerequisites.html

We need to investigate whether running NetworkManager is an issue with openshift sdn.
If it is an issue and fixable then we should fix it otherwise add description in the docs why we recommend NetworkManager service to be truned off.

**Comment by rajatchopra** [comment]
I can't recall what issues we faced with NetworkManager. So the best way so to let it be on when we run openshift-sdn, and find out if the recommendation is stale.

**Comment by dcbw** [comment]
Running NetworkManager should not be an issue for openshift-sdn.  I've been doing all my dev work and testing of the multitenant branches with NM on in the guest images and it does not interfere.  It should not interfere; if it does then we file a bug against NetworkManager and we'll get the NM team to fix it.

**Comment by dcbw** [comment]
Note that you want NetworkManager 0.9.10 (released 04-Jul-2014) or later.  This means that Fedora 20+, Debian Jessie+, Ubuntu 15.04+, etc.  NetworkManager 1.0 (released 19-Dec-2014) is better.

So perhaps update the docs to say that if you have NetworkManager 0.9.8.x or earlier, you may want to turn it off.  But 0.9.10 and later do not interfere with openshift-sdn.

**Comment by sdodson** [comment]
I think the reason that network manager was disabled originally was due to
interactions with test environments that relied on dnsmasq to resolve other
host names in the cluster. *cough*OS1*cough*

https://github.com/openshift/training/issues/193 has a lot of commentary on
the topic

**Comment by dcbw** [comment]
NM has pretty fine-grained control over DNS now, you can drop a file in /etc/NetworkManager/conf.d/ called eg "90-dns.conf" that contains:

[main]
dns=none

and then manage DNS on your own with NM dispatcher scripts or just write static config to resolv.conf yourself.

**Comment by dcbw** [comment]
After adding that file, with NM 1.0+ you send SIGHUP and NM will immediately stop touching resolv.conf.  NM 0.9.10 would need a 'systemctl restart NetworkManager'.

**Comment by rajatchopra** [comment]
Decision: Keep NetworkManager on
Closing this issue as resolved. Please re-open if needed.
