### ISSUE TITLE
Calculate the pmtu instead of hardcoding it

### ISSUE THREAD

**Issue by rajatchopra** [openshift/openshift-sdn#120]
Currently the mtu is hardcoded to 1450. While this works for most cases, its not valid when the assumed underlay is an overlay itself. Use tracepath to reach the master from the node and subtract 50 from it?

**Comment by jeremyeder** [comment]
Performance team decided to shy away from PTMU in the network-throughput tuned profile, collectively felt that changing the MTU on an interface would really surprise sysadmins.  Our implementation idea was PMTU to the default gateway...where else would you measure to?

OpenStack does have something interesting though:  they auto-set the Neutron interface to DHCP-MTU-minus 50.

So, we might need 2 solutions; one for OSE and we might get it for free when running on OpenStack.  Or perhaps adopt OpenStack technique for OSE.  This could be an interesting topic for the f2f.

**Comment by pravisankar** [comment]
We have decided not to change the MTU, default value will be 1450 but there will be config option for the admin to fine tune the value based on their need (like 9000 for jumbo frames).

**Comment by jeremyeder** [comment]
Cool, yeah.   If a user needs the throughput improvement from jumbo frames, they probably want to get that data off of the overlay network.  If they're CPU bottlenecked in a packets-per-second type of workload, that's a separate issue.

**Comment by pravisankar** [comment]
Fix merged.
