### ISSUE TITLE
[multitenant plugin] Handle existing and admin namespaces during startup

### ISSUE THREAD

**Issue by rajatchopra** [openshift/openshift-sdn#129]
Today when we migrate from openshift-ovs-subnet (not multitenant) to the multitenant plugin, we ignore the existing namespaces of the running cluster. This means that all existing namespaces get the default vnid, i.e. 0. This renders all existing namespaces with admin connectivity powers (can read/be read from anyone).
The multitenant plugin should assign VNIDs to existing namespaces also.

There should, however, be a way to specify which namespaces be left as 'admin' namespaces.

**Comment by pravisankar** [comment]
Fixed in https://github.com/openshift/openshift-sdn/pull/176
Existing namespaces are isolated when user migrates from flat to multitenant sdn and admin can turn on/off project isolation/global visibility within the cluster using 'oadm pod-network' CLI cmd.
