### ISSUE TITLE
Perform SDN setup when switching between Flat and Multitenant plugins

### ISSUE THREAD

**Issue by pravisankar** [openshift/openshift-sdn#131]
Currently in the flat/multi-tenant setup scripts, setup_required() is same in both the cases and this causes the user to explicitly delete the lbr0 bridge when switching between flat and multi-tenant plugins and vice versa.
Enhance setup_required() in both the plugins to detect setup requirement when user switches between the plugins.

**Comment by rajatchopra** [comment]
This is a broad issue, and somewhat talked about here: https://github.com/openshift/origin/issues/3940
We need to split the setup file anyway to accommodate docker daemon restarting vs OVS rules.

**Comment by pravisankar** [comment]
Fixed in https://github.com/openshift/openshift-sdn/pull/181
