### ISSUE TITLE
TestIPServe fails sporadically

### ISSUE THREAD

**Issue by danwinship** [openshift/openshift-sdn#134]
TestIPServe fails sporadically in Travis-CI:

    === RUN TestIPServe-2
    --- FAIL: TestIPServe-2 (0.00s)
    	server_test.go:32: Error in connecting to IPAM server
    FAIL
    exit status 1
    FAIL	github.com/openshift/openshift-sdn/pkg/netutils/server	0.005s

eg, https://travis-ci.org/openshift/openshift-sdn/builds/76176233, https://travis-ci.org/openshift/openshift-sdn/builds/76204528, https://travis-ci.org/openshift/openshift-sdn/builds/76209682

It's always the second run that fails... maybe something isn't getting cleaned up correctly after the first one?

**Comment by pravisankar** [comment]
We didn't notice any TestIPServe failures recently, hoping https://github.com/openshift/openshift-sdn/issues/140 fixed it.
Closing the issue for now. We can reopen if it happens again.

**Comment by danwinship** [comment]
Just failed again: https://travis-ci.org/openshift/openshift-sdn/jobs/79471475:

    === RUN TestIPServe-2
    --- FAIL: TestIPServe-2 (0.00s)
    	server_test.go:32: Error in connecting to IPAM server: %v Get http://127.0.0.1:9080/netutils/ip: dial tcp 127.0.0.1:9080: connection refused

(I already fixed the "%v" in git.)
