### ISSUE TITLE
Handle SDN upgrades cleanly

### ISSUE THREAD

**Issue by pravisankar** [openshift/openshift-sdn#153]
SDN upgrades should not interfere with regular code path.
Follow up card for https://github.com/openshift/origin/pull/4615

**Comment by dcbw** [comment]
This may not be exactly what you're talking about here, but https://github.com/openshift/openshift-sdn/pull/268 should help quite a bit if the OVS flow rules change on upgrade.  Previously they would often be stale and cause random failures.
