### ISSUE TITLE
No spec file for RPM package

### ISSUE THREAD

**Issue by nak3** [openshift/openshift-sdn#16]
As far as I checked, there is no specfile for the RPM package. Could you please add it to the source tree? (Red Hat is supposed to have it.)

**Comment by sdodson** [comment]
If you have access to the private forks it's in 'ose-openshift-sdn', we need to get that work moved upstream soon.

**Comment by nak3** [comment]
Oh... I could access to the private repo. Thank you.
But I wish we could include spec file in the source tree for community users.

**Comment by detiber** [comment]
It will be added to the openshif-sdn repo eventually as well, it just hasn't been reviewed upstream yet.

**Comment by nak3** [comment]
Thank you very much.
Now the spec file has been merged. Please feel free to close this report.

**Comment by nak3** [comment]
Thanks a lot. I close this issue by myself.
