### ISSUE TITLE
docker - Error creating default \"bridge\" network: bridge device with non default name lbr0 must be created manually

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-sdn#174]
As discussed earlier today, there seems to be some sort of sdn initialization issue that thus far I've only seen happen on RHEL 7.2 hosts. This happens with docker-1.8.2-5.el7.x86_64 as well as docker-1.7.2-115.el7 (current version in rhel-extras).

http://sdodson.fedorapeople.org/rhel-72-lbr0.tar.gz has NetworkManager debug logs, openshift-master, openshift-node, docker as well as the full journal.

The codebase is current as of https://github.com/openshift/origin/commit/9669d442

**Comment by sdodson** [comment]
CC: @jeder

**Comment by dcbw** [comment]
Seems to be an NM problem in that RHEL 7,2 snapshot, filed as https://bugzilla.redhat.com/show_bug.cgi?id=1269199 and will get fixed in NM.

**Comment by dcbw** [comment]
@sdodson can you retest with RHEL 7.2 final?  I believe this should be fixed now.  Please re-open if it's not!

**Comment by jeremyeder** [comment]
Yep, this is fixed in 7.2.

**Comment by sdodson** [comment]
Yes, this is most definitely fixed in 7.2 GA versions of NetworkManager. Thanks for your help getting details to the right folks.
