### ISSUE TITLE
leaving docker0 around may cause issues

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-sdn#21]
Despite changing /etc/sysconfig/docker and specifying a bridge and then restarting the docker service, it appears that the docker0 bridge still lingers until reboot.

I am not sure if this causes issues as we are creating iptables DNAT rules to forward 172. traffic to the public interface.

However, it still may be prudent for sdn-node to nuke any dockerX interfaces just in case.

What do you think?

**Comment by akram** [comment]
Hi,
I do face a kind of similar issue with a previously created kbr0 interface from a manual configuration
In case this is a different issue, I am opening a new one

**Comment by rajatchopra** [comment]
Another alternative is to hijack the docker0 bridge itself and use it for openshift-sdn purposes. I think the original thought behind not touching docker0 was 'not to destroy something we didnt create'. Will explore.

**Comment by rajatchopra** [comment]
Will be tackled well and forever by this issue: https://github.com/openshift/openshift-sdn/issues/112
Closing this one out.
