### ISSUE TITLE
openshift-sdn fails to delete or add ova bridge

### ISSUE THREAD

**Issue by akram** [openshift/openshift-sdn#22]
Hi,

when running openshift-sdn as an sdn node, it seems that it fails to delete bridge interfaces and to create them at some points.

when doing a ps -ef, I see that the ovs-vsctl del-br br0 gets locked.
Upon subsequent restarts, it seems that the ovs-* command does not terminate properly

**Comment by akram** [comment]
it looks like a problem with openswitch, restarting it unlocked the command and the openshift-sdn node startup finished correctly

But I don't know the cause of the issue, openvswitch has nothing special in its logs

**Comment by rajatchopra** [comment]
Fixed with the new method where we have made the setup idempotent.
Closing this issue, please re-open if any concern remains.
