### ISSUE TITLE
multitenant plugin - index out of range

### ISSUE THREAD

**Issue by Killboy** [openshift/openshift-sdn#246]
Hi,

I have the node service misbehaving on one master in a 3 master native HA setup, the error appears to be related to the multitenant plugin but that could just be a timing thing .. messages are:

Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.647371    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.23.92,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.650819    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.228.0,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.653938    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.232.137,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.656664    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.106.71,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.659173    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.142.228,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.661626    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.98.134,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.664764    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.51.99,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.667840    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.37.75,tp_dst=80,priority=200,reg0=13,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.670909    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.190.75,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.673816    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.117.160,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.676840    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.154.241,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.679672    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.189.87,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.683312    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.164.128,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.686702    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.203.100,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.689916    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.142.216,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.693258    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.204.246,tp_dst=80,priority=200,reg0=15,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.696468    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.209.75,tp_dst=5000,priority=200,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.699460    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.0.1,tp_dst=443,priority=200,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.702600    2233 multitenant.go:82] Output of adding table=4,udp,nw_dst=172.30.0.1,tp_dst=53,priority=200,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.705702    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.0.1,tp_dst=53,priority=200,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.708956    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.222.150,tp_dst=80,priority=200,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.711914    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.209.72,tp_dst=8080,priority=200,reg0=17,actions=output:2:  (<nil>)
Jan 15 09:44:57 master-002 atomic-openshift-node: I0115 09:44:57.715273    2233 multitenant.go:82] Output of adding table=4,tcp,nw_dst=172.30.209.72,tp_dst=8443,priority=200,reg0=17,actions=output:2:  (<nil>)
Jan 15 09:44:58 master-002 atomic-openshift-node: panic: runtime error: index out of range
Jan 15 09:44:58 master-002 atomic-openshift-node: goroutine 68 [running]:
Jan 15 09:44:58 master-002 atomic-openshift-node: runtime.gopanic(0x2623000, 0xc20802a000)
Jan 15 09:44:58 master-002 atomic-openshift-node: /usr/lib/golang/src/runtime/panic.go:425 +0x2a3 fp=0xc208bcd300 sp=0xc208bcd298
Jan 15 09:44:58 master-002 atomic-openshift-node: runtime.panicindex()
... 

Any thoughts?

thanks

**Comment by danwinship** [comment]
You didn't include enough of the panic message, but assuming it continues with something like:

    Dec 05 19:14:46 prod-node-3 origin-node[13019]: github.com/openshift/openshift-sdn/plugins/osdn.newSDNPod(0xc208789538, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    Dec 05 19:14:46 prod-node-3 origin-node[13019]: /builddir/build/BUILD/origin-git-0.a6bb7cd/_thirdpartyhacks/src/github.com/openshift/openshift-sdn/plugins/osdn/osdn.go:122 +0x151 fp=0xc2087893c0 sp=0xc208789328

then this is #214 and is already fixed

**Comment by Killboy** [comment]
Thanks Dan .. any idea if/when this is in OSE?

**Comment by danwinship** [comment]
It's fixed in the upcoming 3.1.1 release.
