### ISSUE TITLE
RFC:  change IPAM defaults to support future scaling targets

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-sdn#262]
This was an internal thread 4 months ago.  Filing an official request since we are planning to bump our scale limits in upcoming releases.

We currently have 10.1.x.0/24 mapped to each node via openshift-sdn, so ~255 pods per node.
If we want to go beyond 255 pods per node, we would need to bump osm_host_subnet_length to I think 9 which would put a /23 on each node.

Since we use the 10.1.0.0/16 prefix for our pod network, we are limited to 255 nodes by default as well.
If we were to allow 510 IPs per node, that would halve our total node scalability.  So at the same time we would need to break out of the 10.1.0.0/16 network.

One option is to make the following customization in our inventory examples:

openshift_master_portal_net=172.30.0.0/16
osm_cluster_network_cidr=10.0.0.0/8
osm_host_subnet_length=9 (equates to /23)

This would provide IP space for 32k nodes, each with ~512 pods per node.

Thoughts ?

**Comment by jeremyeder** [comment]
@danwinship @dcbw  @timothysc @eparis @smarterclayton not sure who else to tag.

**Comment by danwinship** [comment]
The defaults are actually set in origin, not openshift-sdn, and I'd previously filed https://github.com/openshift/origin/pull/6597 about changing them, though with different suggestions. Anyway, let's continue there.

**Comment by pecameron** [comment]
10.0.0.0/8 might be a problem since the lab is also on the 10 net (wstf 10.19.17.0/16?). Maybe 10.0.0.0/9 would be better.
