### ISSUE TITLE
openshift-sdn refuses to (re)start if interface lbr0 has no IP address and docker is already started

### ISSUE THREAD

**Issue by akram** [openshift/openshift-sdn#27]
I have a setup where docket is started through a docker.socket service which uses a socket file to trigger docker startup.

While trying to start or to restart openshift-sdn, restart fails while trying to restart docker which fails  to start because lbr0 does not have an IP address.

The only workaround is to add a bogus IP address to lbr0, which is then directly removed by openshfit-sdn which then succeed in starting docker.

It looks like a circular dependency issue.

**Comment by rajatchopra** [comment]
lbr0 is assigned an IP address by openshift-sdn, before docker is restarted. Can you give the logs of the start failure and the output of 'ip addr show lbr0' after the failure (but before you manually assign any)?

**Comment by rajatchopra** [comment]
Closing this issue. The latest release does not show any symptoms of this issue. Please re-open if still a concern.

**Comment by chmouel** [comment]
@rajatchopra I have seen this happening on my cloud multiple times : 

````
-- Logs begin at Thu 2015-09-24 11:34:17 EDT. --
Oct 06 09:40:55 master.local.openshift.chmouel.com docker[31985]: time="2015-10-06T09:40:55-04:00" level=info msg="+job serveapi(unix:///var/run/docker.sock)"
Oct 06 09:40:55 master.local.openshift.chmouel.com docker[31985]: time="2015-10-06T09:40:55-04:00" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
Oct 06 09:40:55 master.local.openshift.chmouel.com docker[31985]: time="2015-10-06T09:40:55-04:00" level=info msg="+job init_networkdriver()"
Oct 06 09:40:55 master.local.openshift.chmouel.com docker[31985]: Interface lbr0 has no IPv4 addresses
Oct 06 09:40:55 master.local.openshift.chmouel.com docker[31985]: time="2015-10-06T09:40:55-04:00" level=info msg="-job init_networkdriver() = ERR (1)"
Oct 06 09:40:55 master.local.openshift.chmouel.com docker[31985]: time="2015-10-06T09:40:55-04:00" level=fatal msg="Shutting down daemon due to errors: Interface lbr0 has no IPv4 addresses"
Oct 06 09:40:55 master.local.openshift.chmouel.com systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Oct 06 09:40:55 master.local.openshift.chmouel.com systemd[1]: Failed to start Docker Application Container Engine.
```

the ip a was showing something like this : 

````
97: lbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 127.1.1.1/8 brd 127.255.255.255 scope host lbr0
       valid_lft forever preferred_lft forever
```

**Comment by danwinship** [comment]
people are seeing this again: #174

**Comment by dcbw** [comment]
Can everyone who's experiencing this post what version of NetworkManager is running on the nodes?

**Comment by sdodson** [comment]
NetworkManager-1.0.6-12.el7.x86_64 for the hosts that I'm seeing the problem on.
