### ISSUE TITLE
We should not restart docker if we haven't updated the config

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-sdn#29]
openshift-sdn-node restarts docker even in conditions where it doesn't modify the docker config. Does it make sense to only restart docker in the event of configuration change or do we need to ensure it's restarted after openshift-sdn-node because if openshift-sdn-node hasn't been started the bridge may not exist?

**Comment by rajatchopra** [comment]
Will be dealt and taken care of properly with this issue: https://github.com/openshift/openshift-sdn/issues/112

Closing this issue. Please re-open if still a concern.
