### ISSUE TITLE
When SDN is not configured properly, insufficient debug info printed to logs

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-sdn#290]
This may be a Kube issue (if Kube is eating necessary debug info) but starting here.  When running with multi tenant plugin with some system configuration not correct, the only message the Kubelet returns on startup is:

```
E0407 01:05:44.976884   16746 manager.go:1871] Failed to setup network for pod "docker-registry-1-kwj8m_default(5aefb286-fb0f-11e5-83ac-080027c5bfa9)" using network plugins "redhat/openshift-ovs-multitenant": exit status 1; Skipping pod
```

That means that it's impossible for an admin to take the next step and debug why the configuration is inaccurate.  In general, whenever we fail in a flow we should print out necessary info to debug further (I assume in this case stdout/stderr from the execution of the network plugin script).

**Comment by smarterclayton** [comment]
In this case the error output should be part of the error returned from SetUpPod, since the script has taken responsibility for writing the error.  So I would expect ovs.SetUpPod to return something like:

```
out, err := utilexec.New().Command(....)
if err != nil {
  if // is exit code non-zero from command {
    return fmt.Errorf("network setup for pod %q failed (%s) with exit code %d: %v", podNameNamespace, pluginName, exitCode, out)
  }
  return fmt.Errorf("network setup for pod %q failed (%s): %v", ..., err)
}
```

That ensures that the kubelet logs the error so an admin can debug, and in this case the network error gets propagated up.  This is similar to work that's been done with volume plugins - it ensures that the problem is debuggable by the admin / advanced user.

**Comment by smarterclayton** [comment]
The network plugin should not be using `-x` and should be outputting errors where it can

**Comment by danwinship** [comment]
> The network plugin should not be using -x and should be outputting errors where it can

We can only output useful errors if we *do* use -x really. Though if/when we move to doing more stuff in code rather than in a script, we'll be able to return better errors for those parts
