### ISSUE TITLE
multitenant plugin fails on oadm pod-network join-projects

### ISSUE THREAD

**Issue by allen13** [openshift/openshift-sdn#297]
Steps to reproduce:

- Set up an openshift cluster using the redhat/openshift-ovs-multitenant plugin for networking
- Create pods in two different projects
- Make sure those pods can't ping each other since they should be isolated
- Run oadm pod-network join-projects --to=p1 p2
- The two pods still can not ping each other

Error in openshift-node logs:

ovs-vsctl[68003]: ovs|00002|vsctl|ERR|no row "[]" in table QoS

Fix:

Comment out line 106 in openshift-sdn-ovs https://github.com/openshift/openshift-sdn/blob/master/plugins/osdn/ovs/bin/openshift-sdn-ovs#L106
Repeat the above process. The two pods can now ping each other and there is no error in the logs.

Concerns:

How important is it that ovs-vsctl destroy qos ${qos} be run? I assume one day I may run into a case where this is an issue. Additionally, this could be conditionally skipped by checking for []. Maybe I am missing some other config? Should qos have stuff in it? I feel like it will always be empty since this command is run before it: ovs-vsctl clear port ${veth_host} qos

Thanks for your time!

**Comment by dcbw** [comment]
Fixed by https://github.com/openshift/openshift-sdn/pull/272 so it should show up Origin very soon if it's not in there already.

**Comment by allen13** [comment]
Wow thanks! I was looking right at that and didn't notice when I marked the line for the issue.
