### ISSUE TITLE
bridge utils package required for "brctl"

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-sdn#3]
bridge-utils is a required package, in addition to openvswitch.

**Comment by brenton** [comment]
The bridge-utils package comes from RHEL7 so we shouldn't have to do anything special for it to be available.  Does openshift have a dependency on brctl or does openvswitch?  If they former we'll need to make sure a "Requires:" line is added to the specfile.

**Comment by thoraxe** [comment]
`openshift-sdn` has a dependency on `brctl` which is in the `bridge-utils` package which needs nothing special to be installed but is not installed by default with "minimal".

You can do a "minimal" install and `yum -y install openvswitch` and it won't pull in `bridge-utils`.

Further, `openvswitch` currently is **not** shipped in the default EL7 repos - it requires a RHOS repo to be enabled.

I hope that clears it up!

**Comment by brenton** [comment]
We're working it out so that we can ship the same version as RHOS in our own channels.

**Comment by rajatchopra** [comment]
Fixed by @sdodson through commit 2528b9ec7
Closing the issue.
