### ISSUE TITLE
Allow configuration of cluster subnet

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-sdn#30]
We've had one user who has IP and DNS conflicts when using 10.1.0.0/16 for their cluster so we should allow for configuration of this subnet. This is noted as a TODO but wanted to get an issue in to track it.

**Comment by jeremyeder** [comment]
+1

**Comment by brenton** [comment]
@rajatchopra, @mrunalp, any chance we could get this assigned to someone and fixed before next wednesday?

**Comment by mrunalp** [comment]
@brenton we were discussing fixing this as it requires minor changes. Rajat had it on his todo. We will get it done before Wednesday.

**Comment by rajatchopra** [comment]
The feature is available. Closing this issue. Re-open if there are any problems.
