### ISSUE TITLE
We need to add our own higher level errors

### ISSUE THREAD

**Issue by mrunalp** [openshift/openshift-sdn#31]
We shouldn't always bubble up lower errors but should wrap them up in Higher level errors so it makes it easier to understand which subsystem failed.

**Comment by rajatchopra** [comment]
This suggestion has been adopted well with the new integration with OpenShift as a single binary.
The multitenant PR has some more error handling done appropriately.
(https://github.com/openshift/origin/pull/3665)

Closing this issue.
