### ISSUE TITLE
Look into replacing iptables rules by firewalld rules

### ISSUE THREAD

**Issue by mrunalp** [openshift/openshift-sdn#32]
Suggested by @Miciah

**Comment by danwinship** [comment]
I just submitted https://github.com/GoogleCloudPlatform/kubernetes/pull/12396 to make kube's util/iptables be firewalld-aware. Assuming that is accepted, the easy fix here would then be to make openshift-sdn do its iptables setup from go using that, rather than from a shell script like it does now.
