### ISSUE TITLE
IP allocation doesn't allocate IPs according to IPv4 subnetting math

### ISSUE THREAD

**Issue by jeremyeder** [openshift/openshift-sdn#43]
Loop through osdn-docker-run > 255 times and you'll see what I mean:

++ ip netns exec 32545 ip addr add 10.1.0.840/16 dev eth0
Error: an inet prefix is expected rather than "10.1.0.840/16".

**Comment by jeremyeder** [comment]
/etc/openshift-env/used.log

**Comment by rajatchopra** [comment]
Yep. That was a hack to get it going.
I didnt expect this to be run so many times :).
 Will fix.

**Comment by rajatchopra** [comment]
To be clear it is only a bug in the experimental branch sdn_no_lbr and sdn_internal_ports.
We do not need to track this bug/fix for openshift-sdn master.

**Comment by jeremyeder** [comment]
agreed, sorry i should have noted that.

**Comment by mrunalp** [comment]
@jeremyeder We have now added an ip allocator that will be integrated into plugins soon.
