### ISSUE TITLE
don't clobber add_registry and etc

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-sdn#53]
It seems that we're clobbering the `ADD_REGISTRY` directive that's already there when the SDN writes out the new config

**Comment by detiber** [comment]
This will actually be resolved with: https://github.com/openshift/openshift-sdn/issues/52

**Comment by detiber** [comment]
https://github.com/openshift/openshift-sdn/issues/54 has been merged, and openshift-sdn-node no longer clobbers /etc/sysconfig/docker
