### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tcastberg** [openshift/openshift-sdn#71]
As origin 0.5.1 now has altered the layout in etcd the existing release of openshift-sdn (0.1) is outdated. I see that this has been updated in sdn so could we please get a new release which matches origin?

**Comment by rajatchopra** [comment]
Fixed by 
https://github.com/openshift/openshift-sdn/commit/7b5c5d73ab925d50d5403e3ce834e11f13584aa2

**Comment by smarterclayton** [comment]
The issue in beta4 was that the package name changed between beta3 and beta4 and they didn't have the new package.
