### ISSUE TITLE
Need to clear iptables rule to FORWARD -j REJECT --reject-with icmp-host-prohibited

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-sdn#73]
I'm not sure exactly when this became an issue, however on more recent installs, particularly using the openshift-ovs-subnet integrated into openshift, pods can communicate with each other, however iptables seems to be blocking pod access outside of the SDN.

The fix for me seems to be to delete the forward reject rule, though I'm not 100% certain where it's coming from. Perhaps we should clear it when initializing the sdn?

```
iptables -D FORWARD -j REJECT --reject-with icmp-host-prohibited
```

CC: @sosiouxme

**Comment by sosiouxme** [comment]
Confirmed this seems to workaround the issue.

**Comment by detiber** [comment]
Instead of just rejecting the forwarding rule, do we need to add a forwarding rule to allow forwarding traffic from the pods?

**Comment by sdodson** [comment]
@mrunalp what were the proposed iptables changes to address this? We need this in order to ship beta4 otherwise openshift-ovs-subnet is pretty much broken.

**Comment by mrunalp** [comment]
We need to add an accept rule for traffic to the container subnet. Something like
```
iptables -A FORWARD -d 10.0.0.0/16 -j ACCEPT
```

**Comment by rajatchopra** [comment]
Fixed with https://github.com/openshift/openshift-sdn/pull/74
