### ISSUE TITLE
openshift-ovs-subnet script cannot cope with systemd/udev predictable network interface names

### ISSUE THREAD

**Issue by Stephen001** [openshift/openshift-sdn#91]
http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

On suitably new versions of systemd/udev, there is no presumed default physical interface name of 'eth0' created by systemd/udev. As such, openshift-ovs-subnet fails to correctly determine the ifindex of the new veth it is looking to map into the ovs flow. This sometimes results in incorrect mappings of subnets to remote members of the vxlan.

https://github.com/openshift/openshift-sdn/blob/master/ovssubnet/bin/openshift-ovs-subnet#L37

**Comment by dcbw** [comment]
@Stephen001 do you mean that inside the container, the interface is no longer called eth0 because it gets renamed by udev?  Are you attempting to run systemd/udev inside the container?  Last I knew that wasn't supported and udev wasn't used inside containers at all, but perhaps that has changed...

**Comment by dcbw** [comment]
@Stephen001 ping; any chance you could answer the questions above?  Thanks!

**Comment by dcbw** [comment]
Closing this one; please re-open if you have can grab the info requested above or if the problem re-appears.  Thanks!
